name: Linux Desktop (VNC)
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup Previous User
        run: |
          sudo userdel -r roxx >/dev/null 2>&1 || true
          sudo rm -rf /home/roxx

      - name: Create Dynamic User
        run: |
          # Find available UID starting from 2000
          LAST_UID=$(awk -F: '\$3 >= 2000 {print \$3}' /etc/passwd | sort -n | tail -1)
          NEW_UID=$((LAST_UID +1))
          if [ -z "$LAST_UID" ]; then
            NEW_UID=2000
          fi

          # Verify UID is available
          while getent passwd $NEW_UID >/dev/null; do
            NEW_UID=$((NEW_UID +1))
          done

          # Create user with discovered UID
          sudo useradd -m -u $NEW_UID roxx --shell /bin/bash
          echo "roxx:123456" | sudo chpasswd
          sudo usermod -aG sudo roxx
          sudo chown -R roxx:roxx /home/roxx
          sudo chmod 700 /home/roxx

      - name: Auth Ngrok
        run: ngrok config add-authtoken 1vyToVbhRgTWWpr2n4OGWzlDhkC_7MzYHmB9MT1sHGKd8GdgU

      - name: Start Ngrok Tunnel (VNC)
        run: ngrok tcp 5901


    
