name: Cl

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Downloading Essentials
      run: | 
          invoke-WebRequest https://raw.githubusercontent.com/STharanga/FVPS_Files/main/Downloads.bat -OutFile Downloads.bat
          cmd /c Downloads.bat
    - name: Download
      run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
    - run: choco install winrar -y
    - name: Extract
      run: Expand-Archive ngrok.zip
    - name: Auth
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Enabling RDP Access
      run: cmd /c Acess.bat

    - name: Upload Softwares 
      run: cmd /c Uploads.bat        

    - name: Log In To Remote Desktop Protocol
      run: cmd /c start.bat

    - name: Time Count
      run: cmd /c loop.bat
