name: Cl

on: [workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Download/Install
      run: |
          choco install ngrok -y --limit-output --no-progress
          choco install qdir -y --limit-output --no-progress
          choco install winrar -y --limit-output --no-progress
          choco install googledrive -y --limit-output --no-progress
          choco install airexplorer -y --limit-output --no-progress
          choco install ffmpeg -y --limit-output --no-progress
          choco install yt-dlp -y --limit-output --no-progress
          choco install nilesoft-shell -y --limit-output --no-progress
    - name: Auth
      run: ngrok authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Enable TS
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "Asd@123456" -Force)
    - name: Create Account
      run: | 
        net config server /srvcomment:"Windows Server " > errormsg.txt 2>&1 
        REG ADD "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer" /V EnableAutoTray /T REG_DWORD /D 0 /F > errormsg.txt 2>&1
        net user UserX Asd@123456 /add >nul
        net localgroup administrators UserX /add >nul
        net user installer /delete
        ICACLS C:\Windows\Temp /grant UserX:F >nul
        ICACLS C:\Windows\installer /grant UserX:F >nul
        diskperf -Y >nul
        echo Username UserX / runneradmin
        echo Password Asd@123456
    - name: Create Tunnel
      run: ngrok tcp 3389

